#!/usr/bin/env bash
#Displaying numbers from 1 to 100 in a list format, displays Fizzbuzz for multiples of 3 and 5, display fizz for multiples of 3 and buzz for multiple of 5
for ((i = 1; i < 101; i++)); do
    if [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]
    then
	echo "FizzBuzz"
    elif [ $((i % 3)) -eq 0 ]
    then
	echo "Fizz"
    elif [ $((i % 5)) -eq 0 ]
    then
	echo "Buzz"
    else
	echo $i
    fi
done
