#!/usr/bin/env bash
#Using a while loop to display "Best School" and using if, elif and else loops to print bad luck and good luck at the 4th and 8th time respectively
i="0"
while [ $i -lt 10 ]; do
    if [ $i -eq 3 ]
    then
        echo "bad luck"
    elif [ $i -eq 7 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    i=$((i+1))
done
