#!/usr/bin/env bash
#Using a while loop to display number from 1 to 20, using case statemets to display which numbers are bad luck
i="1"
while [ $i -lt 21 ]; do
    echo $i
    case $i in
        4)
	    echo "bad luck from china"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
        17)
	    echo "bad luck from Italy"
	    ;;
	esac
    i=$((i+1))
done
