#!/usr/bin/env bash
#Using if and else to check and display information about the file "school"
file="school"
if [ -s "$file" ]
then
    echo "school file exists"
    if [ -s "$file" ]
    then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    if [ -f "$file" ]
    then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
